// file: IbrowOntology.java generated by ontology bean generator.  DO NOT EDIT, UNLESS YOU ARE REALLY SURE WHAT YOU ARE DOING!
package practica7.ibrow.ontology;

import jade.content.onto.*;
import jade.content.schema.*;

/** file: IbrowOntology.java
 * @author OntologyBeanGenerator v4.1
 * @version 2021/12/24, 19:05:07
 */
public class IbrowOntology extends jade.content.onto.Ontology  {

  private static final long serialVersionUID = -1819682795856872433L;

  //NAME
  public static final String ONTOLOGY_NAME = "ibrow";
  // The singleton instance of this ontology
  private static Ontology theInstance = new IbrowOntology();
  public static Ontology getInstance() {
     return theInstance;
  }


   // VOCABULARY
    public static final String LIBROAGENT_LIBRO="libro";
    public static final String LIBROAGENT="LibroAgent";
    public static final String LIBRO_NOMBRELIBRO="NombreLibro";
    public static final String LIBRO_PRECIO="Precio";
    public static final String LIBRO="Libro";

  /**
   * Constructor
  */
  private IbrowOntology(){ 
    super(ONTOLOGY_NAME, BasicOntology.getInstance());
    try { 

    // adding Concept(s)
    ConceptSchema libroSchema = new ConceptSchema(LIBRO);
    add(libroSchema, practica7.ibrow.ontology.impl.DefaultLibro.class);

    // adding AgentAction(s)
    AgentActionSchema libroAgentSchema = new AgentActionSchema(LIBROAGENT);
    add(libroAgentSchema, practica7.ibrow.ontology.impl.DefaultLibroAgent.class);

    // adding AID(s)

    // adding Predicate(s)


    // adding fields
    libroSchema.add(LIBRO_PRECIO, (TermSchema)getSchema(BasicOntology.FLOAT), ObjectSchema.MANDATORY);
    libroSchema.add(LIBRO_NOMBRELIBRO, (TermSchema)getSchema(BasicOntology.STRING), ObjectSchema.MANDATORY);
    libroAgentSchema.add(LIBROAGENT_LIBRO, libroSchema, ObjectSchema.MANDATORY);

    // adding name mappings

    // adding inheritance

   }catch (java.lang.Exception e) {e.printStackTrace();}
  }
}
